### ISSUE TITLE
SSH executor does not allow to run multiple commands in single step

### ISSUE THREAD

**Issue by timukas** [ErdemOzgen/blackdagger#83]
Hi,

SSH executor works well with a single commands, but multiple commands are not being executed on the remote system.

E.g running ssh command "cp /etc/resolv.conf /tmp/x ; cat /tmp/x" executes only first command on the remote system "cp /etc/resolv.conf /tmp/x".
Second command "cat /tmp/x" is being executed.

Would be cool to be able to run multiple commands from single ssh executor step. Running several ssh executors leave more traces on the remote system(s).

**Comment by ErdemOzgen** [comment]
@timukas ,
Starting for development we can monitor all activities in this branch https://github.com/ErdemOzgen/blackdagger/tree/add-ssh-executor-multiple-commands. @ataseren

**Comment by ErdemOzgen** [comment]
@ataseren Latest commit is working in my test case can you also check with your own test setup.

```yaml
steps:
  - name: step1
    executor:
      type: ssh
      config:
        user: erdem
        ip: 192.168.64.6
        port: 22
        key: /Users/erdem/.ssh/id_rsa
    command: "/usr/sbin/ifconfig"

  - name: step2
    executor:
      type: ssh
      config:
        user: erdem
        ip: 192.168.64.6
        port: 22
        password: changeme
    script: |
      echo "Executing multiple commands:"
      cp /etc/resolv.conf /tmp/x
      cat /tmp/x

```
